---
title: "Assignment#4"
author: "Tyler Cobian"
date: "5/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install the packages
```{r}
library(tidyverse)
library(deSolve)
library(sensitivity)
```

Input the model for forest growth
```{r}
forest<- function(time, initial_kgC, parms){

  
  # define the parms
  early_growth<- parms$early_growth
  later_growth<- parms$later_growth
  K<- parms$K
  canopy_thresh<- parms$canopy_thresh
  temp<- parms$temp
  
  # Set the initial size of forest
kgC = initial_kgC


if (kgC < parms$canopy_thresh) return(list(kgC * parms$later_growth))

if (kgC > parms$canopy_thresh) return(list(kgC * parms$early_growth))
  
if (parms$temp < 0) return(list(kgC * 0))

if (kgC > parms$K) return(list(kgC = parms$K))


}

```

Set up the time and initial kgC
```{r}
time = seq(from=1, to=300, by=1)

initial_kgC = 10
```

Run the ODE solver
```{r}
# set up the parms
parms = list(early_growth = 0.01, later_growth = 2, K = 500, canopy_thresh = 100, temp = 20)

# Run the ODE
results = ode(y = initial_kgC, times = time, func = forest, parms = parms)

head(results)

# clean up the results data and save as dataframe
colnames(results)<- c("time", "kgC")
results_df = as.data.frame(unlist(results))


# plot the results of the ODE run
forest_plot<- ggplot(data = results_df, aes(x = time, y = kgC))+
  geom_line(colour = "cyan4")+
  labs(title = "Dyanmic Forest Growth")+
  theme_minimal()
forest_plot

```

Run a sensativity analysis

```{r Sobel}
forest2 <- function(time, initial_kgC, early_growth, later_growth, K, canopy_thresh, temp){

  
  # define the parms
  early_growth <- early_growth
  later_growth <- later_growth
  K<- K
  canopy_thresh <- canopy_thresh
  temp<- temp
  
  # Set the initial size of forest
  kgC = initial_kgC
  
if (kgC > canopy_thresh) return(kgC * early_growth)
if (kgC < canopy_thresh) return(kgC * later_growth)
if (temp < 0) return(kgC * 0)
if (kgC >= K) return(kgC = K)

}

time = seq(from=1, to=300, by=1)
initial_kgC = 10
early_growth = 0.01
later_growth = 2
K = 500
canopy_thresh = 100
temp = 20

np=10000
early_growth = rnorm(mean=0.1,sd=0.02, n=np) 
later_growth = rnorm(mean=2,sd=0.4, n=np)

# generate two examples of random number from parmeter distributions

X1 = cbind.data.frame(early_growth, later_growth)

# repeat sampling
early_growth = rnorm(mean=0.1,sd=0.02, n=np) 
later_growth = rnorm(mean=2,sd=0.4, n=np)

X2 = cbind.data.frame(early_growth, later_growth)

sens_forest_sobel = sobol2007(model = NULL, X1, X2, nboot = 100)

#parms = list(early_growth = 0.01, later_growth = 2, K = 500, canopy_thresh = 100, temp = 20)

# run model for all parameter sets
res = mapply(FUN=forest2, 
             early_growth=sens_forest_sobel$X$early_growth,
             later_growth=sens_forest_sobel$X$later_growth,
             MoreArgs=list(initial_kgC = 10, K=500, canopy_thresh=100, temp=20))

sens_forest_sobel = sensitivity::tell(sens_forest_sobel, res, res.names="ga")

# first-order indices 
sens_forest_sobel$S

# total sensitivity index 
sens_forest_sobel$T

print(sens_forest_sobel)
plot(sens_forest_sobel)


# make a data frame for plotting
both = cbind.data.frame(sens_forest_sobel$X, gs=sens_forest_sobel$y)

### These plots do not look correct
#look at response of conductance to the two most important variables
#ggplot(both, aes(early_growth, gs))+geom_point()+labs(y="kgC", x="Early Growth")
#ggplot(both, aes(later_growth, gs))+geom_point()+labs(y="kgC", x="Later Growth")

```










